"""
report_sections.py
~~~~~~~~~~~~~~~~~~
All PDF section builder functions extracted from report_generator.py.
Each function builds one section of the report story.
"""
from __future__ import annotations

import logging
from typing import Any

from reportlab.lib import colors
from reportlab.lib.styles import ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import (
    Paragraph,
    Spacer,
    Table,
    TableStyle,
    PageBreak,
)
from reportlab.platypus.flowables import Flowable

from app.services.theme import Brand
from app.services.report_styles import (
    ReportMetadata,
    _decode_image,
    _build_styled_table,
    _divider,
)

logger = logging.getLogger(__name__)


# ─── Section Builders ────────────────────────────────────────────────────────

def _build_title_page(filename: str, styles: dict[str, ParagraphStyle]) -> list[Flowable]:
    """Build the title page."""
    story: list[Flowable] = []
    story.append(Spacer(1, 2.0 * inch))
    story.append(Paragraph(f"Data Analysis Report", styles["ReportTitle"]))
    story.append(Spacer(1, 0.15 * inch))
    story.append(Paragraph(f"Source: {filename}", styles["ReportSubtitle"]))
    story.append(Spacer(1, 0.25 * inch))
    story.append(Paragraph("Generated by GetReport AI", styles["ReportSubtitle"]))
    story.append(PageBreak())
    logger.info("Title page built.")
    return story


def _build_metadata_section(
    analysis_results: dict[str, Any],
    styles: dict[str, ParagraphStyle],
    meta: ReportMetadata,
) -> list[Flowable]:
    """Build a dataset overview section showing row/column counts and column types."""
    if "metadata" not in analysis_results or not analysis_results["metadata"]:
        meta.sections_skipped.append({"section": "Dataset Overview", "reason": "No metadata available."})
        return []

    story: list[Flowable] = []
    metadata = analysis_results["metadata"]
    story.append(Paragraph("Dataset Overview", styles["SectionHeading"]))
    story.append(Spacer(1, 0.1 * inch))

    table_data = [["Property", "Value"]]
    display_keys = {
        "total_rows": "Total Rows", "total_columns": "Total Columns",
        "numeric_columns": "Numeric Columns", "categorical_columns": "Categorical Columns",
        "total_missing_values": "Missing Values", "missing_value_pct": "Missing Value %",
    }
    for key, label in display_keys.items():
        if key in metadata:
            val = metadata[key]
            formatted = f"{val}%" if "pct" in key else str(val)
            table_data.append([label, formatted])

    story.append(_build_styled_table(table_data, col_widths=[3.0 * inch, 2.5 * inch]))
    story.extend(_divider())
    meta.sections_included.append("Dataset Overview")
    return story


def _build_semantic_analysis_section(
    analysis_results: dict[str, Any],
    styles: dict[str, ParagraphStyle],
    meta: ReportMetadata,
) -> list[Flowable]:
    """Build the Semantic Intelligence section."""
    semantic = analysis_results.get("semantic_analysis")
    if not semantic:
        meta.sections_skipped.append({"section": "Data Intelligence", "reason": "Semantic analysis not available."})
        return []

    story: list[Flowable] = []
    story.append(Paragraph("Data Intelligence", styles["SectionHeading"]))
    story.append(Spacer(1, 0.1 * inch))

    domain_info = semantic.get("domain", {})
    domain_name = domain_info.get("primary", "Unknown").replace("_", " ").title()
    confidence = domain_info.get("confidence", 0)
    matched_keywords = domain_info.get("matched_keywords", [])

    domain_text = f"<b>Detected Domain:</b> {domain_name} ({int(confidence * 100)}% confidence)"
    if matched_keywords:
        domain_text += f"<br/><i>Matched patterns: {', '.join(matched_keywords[:8])}</i>"
    story.append(Paragraph(domain_text, styles["Insight"]))
    story.append(Spacer(1, 0.15 * inch))

    column_roles = semantic.get("column_roles", {})
    if column_roles:
        story.append(Paragraph("<b>Column Classification</b>", styles["TableCaption"]))
        story.append(Spacer(1, 0.05 * inch))
        role_groups: dict[str, list[str]] = {}
        for col, info in column_roles.items():
            role = info.get("role", "unknown")
            role_groups.setdefault(role, []).append(col)

        role_data = [["Column Type", "Columns"]]
        role_display = {
            "identifier": "Identifier (excluded)", "name_label": "Name/Label (excluded)",
            "datetime": "Date/Time", "target_metric": "Target Metric",
            "predictor_metric": "Predictor", "percentage_metric": "Percentage",
            "financial_metric": "Financial", "dimension": "Dimension/Category",
            "boolean": "Boolean", "unknown": "Unclassified",
        }
        for role, cols in role_groups.items():
            role_label = role_display.get(role, role.title())
            col_list = ", ".join(cols[:5])
            if len(cols) > 5:
                col_list += f" (+{len(cols)-5} more)"
            role_data.append([role_label, col_list])
        story.append(_build_styled_table(role_data, col_widths=[2.2 * inch, 4.0 * inch]))
        story.append(Spacer(1, 0.15 * inch))

    suggestions = semantic.get("suggested_analysis", [])
    if suggestions:
        story.append(Paragraph("<b>Recommended Analysis</b>", styles["TableCaption"]))
        story.append(Spacer(1, 0.05 * inch))
        for i, sugg in enumerate(suggestions[:5], 1):
            cols = sugg.get("columns", [])
            reason = sugg.get("reason", "")
            if len(cols) >= 2:
                sugg_text = f"{i}. <b>{cols[0]}</b> ↔ <b>{cols[1]}</b>: {reason}"
                story.append(Paragraph(sugg_text, styles["Normal"]))
        story.append(Spacer(1, 0.1 * inch))

    analytical = semantic.get("analytical_columns", [])
    identifiers = semantic.get("identifier_columns", [])
    dimensions = semantic.get("dimension_columns", [])
    summary_text = (
        f"<b>Analysis Scope:</b> {len(analytical)} analytical columns, "
        f"{len(identifiers)} excluded identifiers, "
        f"{len(dimensions)} categorical dimensions"
    )
    story.append(Paragraph(summary_text, styles["Normal"]))
    story.extend(_divider())
    meta.sections_included.append("Data Intelligence")
    return story


def _build_cleaning_section(
    analysis_results: dict[str, Any],
    styles: dict[str, ParagraphStyle],
    meta: ReportMetadata,
) -> list[Flowable]:
    """Build the data cleaning summary section."""
    if "cleaning_report" not in analysis_results or not analysis_results["cleaning_report"]:
        meta.sections_skipped.append({"section": "Cleaning Summary", "reason": "No cleaning report available."})
        return []

    story: list[Flowable] = []
    report = analysis_results["cleaning_report"]
    story.append(Paragraph("Data Cleaning Summary", styles["SectionHeading"]))
    story.append(Spacer(1, 0.1 * inch))

    table_data = [["Action Taken", "Count"]]
    actions = {
        "empty_rows_dropped": "Empty Rows Removed", "empty_columns_dropped": "Empty Columns Removed",
        "duplicate_rows_removed": "Duplicate Rows Removed", "numeric_nans_filled": "Numeric NaNs Filled (→ 0)",
        "categorical_nans_filled": "Categorical NaNs Filled (→ Unknown)",
    }
    for key, label in actions.items():
        if key in report:
            table_data.append([label, str(report[key])])

    if report.get("columns_renamed"):
        table_data.append(["", ""])
        table_data.append(["Columns Renamed", ""])
        table_data.append(["Original Name", "New Name"])
        for old, new in report["columns_renamed"].items():
            table_data.append([old, new])

    story.append(_build_styled_table(table_data, col_widths=[3.5 * inch, 2.0 * inch]))
    story.extend(_divider())
    meta.sections_included.append("Cleaning Summary")
    return story


def _build_comparison_section(
    analysis_results: dict[str, Any],
    styles: dict[str, ParagraphStyle],
    meta: ReportMetadata,
) -> list[Flowable]:
    """Build the Data Quality Improvement section (Before vs After)."""
    comp = analysis_results.get("comparison_report")
    if not comp:
        meta.sections_skipped.append({"section": "Quality Comparison", "reason": "No comparison data."})
        return []

    story: list[Flowable] = []
    story.append(Paragraph("Data Quality Improvement", styles["SectionHeading"]))
    story.append(Paragraph(
        "Impact assessment showing data quality metrics before and after cleaning.",
        styles["Body"]
    ))
    story.append(Spacer(1, 0.1 * inch))

    summary = comp.get("summary", {})
    if summary:
        comp_before = summary.get("completeness", {}).get("before", 0)
        comp_after = summary.get("completeness", {}).get("after", 0)
        comp_delta = summary.get("completeness", {}).get("delta", 0)
        uniq_before = summary.get("uniqueness", {}).get("before", 0)
        uniq_after = summary.get("uniqueness", {}).get("after", 0)
        uniq_delta = summary.get("uniqueness", {}).get("delta", 0)

        def color_delta(val, suffix="%"):
            color = "#16a34a" if val > 0 else "#dc2626" if val < 0 else "#6b7280"
            sign = "+" if val > 0 else ""
            return f"<font color='{color}'><b>{sign}{val}{suffix}</b></font>"

        table_data = [
            ["Metric", "Before", "After", "Improvement"],
            ["Completeness Score", f"{comp_before}%", f"{comp_after}%", color_delta(comp_delta)],
            ["Uniqueness Score", f"{uniq_before}%", f"{uniq_after}%", color_delta(uniq_delta)],
            ["Rows", f"{summary.get('rows', {}).get('before')}", f"{summary.get('rows', {}).get('after')}",
             color_delta(summary.get('rows', {}).get('delta', 0), "")],
        ]
        story.append(_build_styled_table(table_data))
        story.append(Spacer(1, 0.15 * inch))

        cols = comp.get("columns", {})
        improved_cols = []
        for col_name, data in cols.items():
            for m in data.get("metrics", []):
                if m["metric"] == "missing_count" and m["delta"] < 0:
                    improved_cols.append((col_name, abs(m["delta"])))

        if improved_cols:
            improved_cols.sort(key=lambda x: x[1], reverse=True)
            top_Improvements = improved_cols[:5]
            story.append(Paragraph("<b>Top Recovered Columns</b> (Missing Values Fixed)", styles["TableCaption"]))
            story.append(Spacer(1, 0.05 * inch))
            imp_data = [["Column", "Missing Values Fixed"]]
            for col, count in top_Improvements:
                imp_data.append([col, f"{int(count)}"])
            story.append(_build_styled_table(imp_data, col_widths=[4.0 * inch, 2.0 * inch]))

    story.extend(_divider())
    meta.sections_included.append("Quality Comparison")
    return story


def _build_executive_summary(
    analysis_results: dict[str, Any],
    styles: dict[str, ParagraphStyle],
    meta: ReportMetadata,
) -> list[Flowable]:
    """Build the executive summary with quality grade, highlights, and stats."""
    story: list[Flowable] = []
    story.append(Paragraph("Executive Summary", styles["SectionHeading"]))
    story.append(Spacer(1, 0.1 * inch))

    confidence_data = analysis_results.get("confidence_scores")
    if confidence_data:
        dataset_grade = confidence_data.get("dataset_grade", "N/A")
        dataset_conf = confidence_data.get("dataset_confidence", 0)
        high_count = confidence_data.get("high_confidence_count", 0)
        low_count = confidence_data.get("low_confidence_count", 0)
        grade_colors = {
            "A": colors.HexColor("#22c55e"), "B": colors.HexColor("#3b82f6"),
            "C": colors.HexColor("#eab308"), "D": colors.HexColor("#f97316"),
            "F": colors.HexColor("#ef4444"),
        }
        grade_color = grade_colors.get(dataset_grade, colors.gray)
        quality_text = f"""
        <b>Overall Data Quality: Grade {dataset_grade}</b> ({dataset_conf:.0f}% confidence)<br/>
        <font size="9">{high_count} high-confidence columns | {low_count} low-confidence columns</font>
        """
        quality_para = Paragraph(quality_text.strip(), styles["Body"])
        quality_table = Table([[quality_para]], colWidths=[5.5 * inch])
        quality_table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#f8fafc")),
            ("LEFTPADDING", (0, 0), (-1, -1), 14), ("RIGHTPADDING", (0, 0), (-1, -1), 14),
            ("TOPPADDING", (0, 0), (-1, -1), 10), ("BOTTOMPADDING", (0, 0), (-1, -1), 10),
            ("BOX", (0, 0), (-1, -1), 2, grade_color),
        ]))
        story.append(quality_table)
        story.append(Spacer(1, 0.15 * inch))
        critical = confidence_data.get("critical_issues", [])
        if critical:
            issues_text = "<b>Issues Requiring Attention:</b><br/>" + "<br/>".join(f"• {i}" for i in critical[:3])
            story.append(Paragraph(issues_text, styles["Body"]))
            story.append(Spacer(1, 0.1 * inch))

    metadata = analysis_results.get("metadata", {})
    if metadata:
        rows = metadata.get("total_rows", "?")
        cols_count = metadata.get("total_columns", "?")
        num_cols = metadata.get("numeric_columns", 0)
        cat_cols = metadata.get("categorical_columns", 0)
        rows_fmt = f"{rows:,}" if isinstance(rows, (int, float)) else str(rows)
        story.append(Paragraph(
            f"<b>Dataset:</b> {rows_fmt} rows × {cols_count} columns ({num_cols} numeric, {cat_cols} categorical)",
            styles["Body"]
        ))
        story.append(Spacer(1, 0.1 * inch))

    semantic = analysis_results.get("semantic_analysis")
    if semantic:
        domain_info = semantic.get("domain", {})
        domain_name = domain_info.get("primary", "Unknown").replace("_", " ").title()
        confidence = domain_info.get("confidence", 0)
        story.append(Paragraph(
            f"<b>Detected Domain:</b> {domain_name} ({int(confidence * 100)}% confidence)",
            styles["Body"]
        ))
        story.append(Spacer(1, 0.15 * inch))

    if "summary" not in analysis_results or not analysis_results["summary"]:
        meta.sections_skipped.append({"section": "Executive Summary Stats", "reason": "No summary stats available."})
    else:
        summary = analysis_results["summary"]
        story.append(Paragraph("<b>Descriptive Statistics</b>", styles["SubHeading"]))
        story.append(Spacer(1, 0.05 * inch))
        for col_name, metrics in summary.items():
            story.append(Paragraph(f"<i>{col_name}</i>", styles["TableCaption"]))
            table_data = [["Metric", "Value"]]
            for k, v in metrics.items():
                val = f"{v:.2f}" if isinstance(v, (int, float)) else str(v)
                table_data.append([k.capitalize(), val])
            story.append(_build_styled_table(table_data, col_widths=[3.0 * inch, 2.5 * inch]))
            story.append(Spacer(1, 0.1 * inch))

    story.extend(_divider())
    meta.sections_included.append("Executive Summary")
    return story


def _build_insights_section(
    analysis_results: dict[str, Any],
    styles: dict[str, ParagraphStyle],
    meta: ReportMetadata,
) -> list[Flowable]:
    """Build the AI Insights section."""
    if "insights" not in analysis_results or not analysis_results["insights"]:
        meta.sections_skipped.append({"section": "AI Insights", "reason": "No insights text available."})
        return []

    story: list[Flowable] = []
    insights_text = analysis_results["insights"]
    story.append(Paragraph("AI-Generated Insights", styles["SectionHeading"]))
    story.append(Spacer(1, 0.1 * inch))

    insight_para = Paragraph(insights_text.replace("\n", "<br/>"), styles["InsightText"])
    insight_table = Table([[insight_para]], colWidths=[6.0 * inch])
    insight_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), Brand.INSIGHT_BG),
        ("LEFTPADDING", (0, 0), (-1, -1), 14), ("RIGHTPADDING", (0, 0), (-1, -1), 14),
        ("TOPPADDING", (0, 0), (-1, -1), 12), ("BOTTOMPADDING", (0, 0), (-1, -1), 12),
        ("BOX", (0, 0), (-1, -1), 1, Brand.ACCENT_LIGHT),
    ]))
    story.append(insight_table)
    story.extend(_divider())
    meta.sections_included.append("AI Insights")
    return story


def _build_correlations_section(
    analysis_results: dict[str, Any],
    styles: dict[str, ParagraphStyle],
    meta: ReportMetadata,
) -> list[Flowable]:
    """Build the strong correlations section."""
    if "strong_correlations" not in analysis_results or not analysis_results["strong_correlations"]:
        meta.sections_skipped.append({"section": "Correlations", "reason": "No strong correlations found."})
        return []

    story: list[Flowable] = []
    story.append(Paragraph("Strong Correlations", styles["SectionHeading"]))
    story.append(Spacer(1, 0.1 * inch))
    story.append(Paragraph(
        "The following column pairs have a notably strong statistical relationship (|r| ≥ 0.7).",
        styles["Body"]
    ))
    story.append(Spacer(1, 0.1 * inch))

    table_data = [["Column A", "Column B", "r Value", "Direction", "Strength"]]
    for pair in analysis_results["strong_correlations"]:
        table_data.append([
            str(pair.get("column_a", "—")), str(pair.get("column_b", "—")),
            str(pair.get("r_value", "—")), str(pair.get("direction", "—")).capitalize(),
            str(pair.get("strength", "—")).capitalize(),
        ])
    col_widths = [1.3 * inch, 1.3 * inch, 1.0 * inch, 1.2 * inch, 1.2 * inch]
    story.append(_build_styled_table(table_data, col_widths=col_widths))
    story.extend(_divider())
    meta.sections_included.append("Strong Correlations")
    return story


def _build_outliers_section(
    analysis_results: dict[str, Any],
    styles: dict[str, ParagraphStyle],
    meta: ReportMetadata,
) -> list[Flowable]:
    """Build the outliers section."""
    if "outliers" not in analysis_results or not analysis_results["outliers"]:
        meta.sections_skipped.append({"section": "Outliers", "reason": "No outliers detected."})
        return []

    story: list[Flowable] = []
    story.append(Paragraph("Outlier Detection", styles["SectionHeading"]))
    story.append(Spacer(1, 0.1 * inch))
    story.append(Paragraph(
        "Values falling outside 1.5× the interquartile range (IQR) are flagged as outliers.",
        styles["Body"]
    ))
    story.append(Spacer(1, 0.1 * inch))

    table_data = [["Column", "Outlier Count", "% of Data", "Lower Bound", "Upper Bound"]]
    for col, info in analysis_results["outliers"].items():
        table_data.append([
            col, str(info.get("count", "—")), f"{info.get('percentage', 0):.1f}%",
            f"{info.get('lower_bound', '—')}", f"{info.get('upper_bound', '—')}",
        ])
    col_widths = [1.6 * inch, 1.1 * inch, 1.0 * inch, 1.2 * inch, 1.2 * inch]
    story.append(_build_styled_table(table_data, col_widths=col_widths))
    story.extend(_divider())
    meta.sections_included.append("Outlier Detection")
    return story


def _build_categorical_section(
    analysis_results: dict[str, Any],
    styles: dict[str, ParagraphStyle],
    meta: ReportMetadata,
) -> list[Flowable]:
    """Build the categorical distribution section."""
    if "categorical_distribution" not in analysis_results or not analysis_results["categorical_distribution"]:
        meta.sections_skipped.append({"section": "Categorical Distribution", "reason": "No categorical data."})
        return []

    story: list[Flowable] = []
    story.append(Paragraph("Categorical Distributions", styles["SectionHeading"]))
    story.append(Spacer(1, 0.1 * inch))

    for col_name, col_data in analysis_results["categorical_distribution"].items():
        story.append(Paragraph(f"{col_name}", styles["SubHeading"]))
        categories = col_data.get("categories", {})
        if not categories:
            continue
        table_data = [["Category", "Count", "Percentage"]]
        for cat_name, cat_info in categories.items():
            table_data.append([
                str(cat_name), str(cat_info.get("count", "—")),
                f"{cat_info.get('percentage', 0):.1f}%",
            ])
        col_widths = [3.2 * inch, 1.3 * inch, 1.3 * inch]
        story.append(_build_styled_table(table_data, col_widths=col_widths))
        story.append(Spacer(1, 0.15 * inch))

    story.extend(_divider())
    meta.sections_included.append("Categorical Distribution")
    return story


def _build_quality_flags_section(
    analysis_results: dict[str, Any],
    styles: dict[str, ParagraphStyle],
    meta: ReportMetadata,
) -> list[Flowable]:
    """Build the data quality flags section."""
    if "column_quality_flags" not in analysis_results or not analysis_results["column_quality_flags"]:
        meta.sections_skipped.append({"section": "Quality Flags", "reason": "No quality flags."})
        return []

    story: list[Flowable] = []
    story.append(Paragraph("Data Quality Flags", styles["SectionHeading"]))
    story.append(Spacer(1, 0.1 * inch))
    story.append(Paragraph(
        "The following columns have data-quality issues that may affect analysis accuracy.",
        styles["Body"]
    ))
    story.append(Spacer(1, 0.1 * inch))

    for col_name, flags in analysis_results["column_quality_flags"].items():
        flag_text = "<br/>".join(f"⚠ {flag}" for flag in flags)
        flag_para = Paragraph(f"<b>{col_name}</b><br/>{flag_text}", styles["WarningText"])
        warning_box = Table([[flag_para]], colWidths=[6.0 * inch])
        warning_box.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, -1), Brand.WARNING_BG),
            ("LEFTPADDING", (0, 0), (-1, -1), 12), ("RIGHTPADDING", (0, 0), (-1, -1), 12),
            ("TOPPADDING", (0, 0), (-1, -1), 8), ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
            ("BOX", (0, 0), (-1, -1), 1, Brand.WARNING_BORDER),
        ]))
        story.append(warning_box)
        story.append(Spacer(1, 0.1 * inch))

    story.extend(_divider())
    meta.sections_included.append("Data Quality Flags")
    return story


def _build_visualizations(
    charts: dict[str, Any],
    styles: dict[str, ParagraphStyle],
    meta: ReportMetadata,
) -> list[Flowable]:
    """Build all chart/visualization sections."""
    story: list[Flowable] = []
    has_any_chart = False

    if "correlation_heatmap" in charts and charts["correlation_heatmap"]:
        story.append(Paragraph("Correlation Analysis", styles["SectionHeading"]))
        story.append(Spacer(1, 0.1 * inch))
        img = _decode_image(charts["correlation_heatmap"], 6 * inch, 4.5 * inch, "Correlation Heatmap", meta)
        if img:
            story.append(img)
            story.append(Spacer(1, 0.25 * inch))
            has_any_chart = True
        else:
            story.append(Paragraph("Correlation heatmap could not be rendered.", styles["Body"]))

    if "distributions" in charts and charts["distributions"]:
        story.append(Paragraph("Feature Distributions", styles["SectionHeading"]))
        for dist in charts["distributions"]:
            col_label = dist.get("column", "Unknown")
            story.append(Paragraph(f"Distribution of {col_label}", styles["SubHeading"]))
            img = _decode_image(dist.get("image", ""), 5 * inch, 3 * inch, f"Distribution: {col_label}", meta)
            if img:
                story.append(img)
                story.append(Spacer(1, 0.1 * inch))
                has_any_chart = True
            else:
                story.append(Paragraph(f"Distribution chart for '{col_label}' could not be rendered.", styles["Body"]))
                story.append(Spacer(1, 0.1 * inch))

    if "bar_charts" in charts and charts["bar_charts"]:
        story.append(Paragraph("Category Comparisons", styles["SectionHeading"]))
        for bar in charts["bar_charts"]:
            col_label = bar.get("column", "Unknown")
            story.append(Paragraph(f"Bar Chart: {col_label}", styles["SubHeading"]))
            img = _decode_image(bar.get("image", ""), 5.5 * inch, 3.5 * inch, f"Bar Chart: {col_label}", meta)
            if img:
                story.append(img)
                story.append(Spacer(1, 0.15 * inch))
                has_any_chart = True
            else:
                story.append(Paragraph(f"Bar chart for '{col_label}' could not be rendered.", styles["Body"]))

    if "boxplots" in charts and charts["boxplots"]:
        story.append(Paragraph("Category vs Numeric Analysis", styles["SectionHeading"]))
        for box in charts["boxplots"]:
            col_label = box.get("column", "Unknown")
            story.append(Paragraph(f"Spread: {col_label}", styles["SubHeading"]))
            img = _decode_image(box.get("image", ""), 5.5 * inch, 4 * inch, f"Boxplot: {col_label}", meta)
            if img:
                story.append(img)
                story.append(Spacer(1, 0.15 * inch))
                has_any_chart = True
            else:
                story.append(Paragraph(f"Boxplot for '{col_label}' could not be rendered.", styles["Body"]))

    if "trend_charts" in charts and charts["trend_charts"]:
        story.append(Paragraph("Trend Analysis", styles["SectionHeading"]))
        for trend in charts["trend_charts"]:
            col_label = trend.get("column", "Unknown")
            story.append(Paragraph(f"Trend: {col_label}", styles["SubHeading"]))
            img = _decode_image(trend.get("image", ""), 5.5 * inch, 3.0 * inch, f"Trend: {col_label}", meta)
            if img:
                story.append(img)
                story.append(Spacer(1, 0.15 * inch))
                has_any_chart = True
            else:
                story.append(Paragraph(f"Trend chart for '{col_label}' could not be rendered.", styles["Body"]))

    if "pie_charts" in charts and charts["pie_charts"]:
        story.append(Paragraph("Composition Analysis", styles["SectionHeading"]))
        for pie in charts["pie_charts"]:
            col_label = pie.get("column", "Unknown")
            story.append(Paragraph(f"Composition: {col_label}", styles["SubHeading"]))
            img = _decode_image(pie.get("image", ""), 4.0 * inch, 4.0 * inch, f"Pie Chart: {col_label}", meta)
            if img:
                story.append(img)
                story.append(Spacer(1, 0.15 * inch))
                has_any_chart = True
            else:
                story.append(Paragraph(f"Pie chart for '{col_label}' could not be rendered.", styles["Body"]))

    if has_any_chart:
        story.extend(_divider())
        meta.sections_included.append("Visualizations")
    else:
        meta.sections_skipped.append({"section": "Visualizations", "reason": "No charts could be rendered."})

    return story


# ─── Tier 1: Statistical Deep Dive ──────────────────────────────────────────

def _build_advanced_stats_section(
    analysis_results: dict[str, Any],
    styles: dict[str, ParagraphStyle],
    meta: ReportMetadata,
) -> list[Flowable]:
    """Build section showing skewness/kurtosis for non-normal distributions."""
    advanced = analysis_results.get("advanced_stats")
    if not advanced:
        meta.sections_skipped.append({"section": "Advanced Stats", "reason": "No advanced stats available."})
        return []

    story: list[Flowable] = []
    story.append(Paragraph("Distribution Shape Analysis", styles["SectionHeading"]))
    story.append(Spacer(1, 0.1 * inch))

    notable = [(col, stats) for col, stats in advanced.items()
               if abs(stats.get("skewness", 0)) > 1 or abs(stats.get("kurtosis", 0)) > 3]

    if notable:
        table_data = [["Column", "Skewness", "Kurtosis", "Interpretation"]]
        for col, stats in notable[:10]:
            skew = stats.get("skewness", 0)
            kurt = stats.get("kurtosis", 0)
            interp = "Right-skewed" if skew > 1 else "Left-skewed" if skew < -1 else "Normal"
            if abs(kurt) > 3:
                interp += ", Heavy tails" if kurt > 3 else ", Light tails"
            table_data.append([col, f"{skew:.2f}", f"{kurt:.2f}", interp])
        story.append(_build_styled_table(table_data))
    else:
        story.append(Paragraph("All numeric columns appear normally distributed.", styles["Body"]))

    story.extend(_divider())
    meta.sections_included.append("Advanced Stats")
    return story


def _build_multicollinearity_section(
    analysis_results: dict[str, Any],
    styles: dict[str, ParagraphStyle],
    meta: ReportMetadata,
) -> list[Flowable]:
    """Build section showing highly correlated feature pairs."""
    multicol = analysis_results.get("multicollinearity")
    if not multicol:
        meta.sections_skipped.append({"section": "Multicollinearity", "reason": "No multicollinearity data."})
        return []

    story: list[Flowable] = []
    story.append(Paragraph("Multicollinearity Analysis", styles["SectionHeading"]))
    story.append(Spacer(1, 0.1 * inch))

    if multicol:
        table_data = [["Feature 1", "Feature 2", "Correlation"]]
        for item in multicol[:10]:
            features = item.get("features", ["?", "?"])
            corr = item.get("correlation", 0)
            table_data.append([features[0], features[1], f"{corr:.3f}"])
        story.append(_build_styled_table(table_data))
        story.append(Spacer(1, 0.1 * inch))
        story.append(Paragraph(
            "<i>High correlation suggests potential redundancy. Consider removing one feature from each pair.</i>",
            styles["Body"]
        ))
    else:
        story.append(Paragraph("No highly correlated feature pairs detected.", styles["Body"]))

    story.extend(_divider())
    meta.sections_included.append("Multicollinearity")
    return story


def _build_time_series_section(
    analysis_results: dict[str, Any],
    styles: dict[str, ParagraphStyle],
    meta: ReportMetadata,
) -> list[Flowable]:
    """Build section for time-series analysis (trend/seasonality)."""
    time_series = analysis_results.get("time_series_analysis")
    if not time_series or not time_series.get("has_time_series"):
        meta.sections_skipped.append({"section": "Time-Series Analysis", "reason": "No time-series data."})
        return []

    story: list[Flowable] = []
    story.append(Paragraph("Time-Series Analysis", styles["SectionHeading"]))
    story.append(Spacer(1, 0.1 * inch))

    time_col = time_series.get("time_column", "Unknown")
    story.append(Paragraph(f"<b>Time Column:</b> {time_col}", styles["Body"]))
    story.append(Spacer(1, 0.1 * inch))

    analyses = time_series.get("analyses", {})
    if analyses:
        table_data = [["Column", "Trend", "Strength", "Seasonality"]]
        for col, data in analyses.items():
            trend = data.get("trend", {})
            season = data.get("seasonality", {})
            trend_str = trend.get("direction", "None") if trend.get("detected") else "None"
            strength_str = trend.get("strength", "-") if trend.get("detected") else "-"
            season_str = season.get("primary_pattern", "-") if season.get("detected") else "None"
            table_data.append([col, trend_str, strength_str, season_str])
        story.append(_build_styled_table(table_data))

    story.extend(_divider())
    meta.sections_included.append("Time-Series Analysis")
    return story


# ─── Tier 2: Advanced Intelligence ──────────────────────────────────────────

def _build_feature_engineering_section(
    analysis_results: dict[str, Any],
    styles: dict[str, ParagraphStyle],
    meta: ReportMetadata,
) -> list[Flowable]:
    """Build section showing ML-ready feature engineering recommendations with summary."""
    fe = analysis_results.get("feature_engineering")
    if not fe:
        meta.sections_skipped.append({"section": "Feature Engineering", "reason": "No feature engineering data."})
        return []

    story: list[Flowable] = []
    story.append(Paragraph("ML Feature Engineering", styles["SectionHeading"]))
    story.append(Paragraph(
        "Intelligent recommendations to prepare your data for machine learning models.",
        styles["Body"]
    ))
    story.append(Spacer(1, 0.1 * inch))

    enc_count = len(fe.get("encoding_recommendations", []))
    scale_count = len(fe.get("scaling_recommendations", []))
    extract_count = len(fe.get("feature_extraction", []))

    if enc_count + scale_count + extract_count > 0:
        summary_text = f"""
        <b>Ready-to-use suggestions:</b> {enc_count} encoding, {scale_count} scaling, {extract_count} feature extraction
        """
        summary_para = Paragraph(summary_text.strip(), styles["Body"])
        summary_table = Table([[summary_para]], colWidths=[5.8 * inch])
        summary_table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#f0fdf4")),
            ("LEFTPADDING", (0, 0), (-1, -1), 12), ("RIGHTPADDING", (0, 0), (-1, -1), 12),
            ("TOPPADDING", (0, 0), (-1, -1), 8), ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
            ("BOX", (0, 0), (-1, -1), 1, colors.HexColor("#22c55e")),
        ]))
        story.append(summary_table)
        story.append(Spacer(1, 0.15 * inch))

    encodings = fe.get("encoding_recommendations", [])
    if encodings:
        story.append(Paragraph("<b>Categorical Encoding</b>", styles["TableCaption"]))
        story.append(Spacer(1, 0.05 * inch))
        encoding_colors = {
            "one_hot": colors.HexColor("#dbeafe"), "label": colors.HexColor("#dcfce7"),
            "target": colors.HexColor("#fef3c7"), "binary": colors.HexColor("#ede9fe"),
            "hash": colors.HexColor("#fee2e2"),
        }
        table_data = [["Column", "Recommended", "Reason"]]
        row_colors = []
        for enc in encodings[:8]:
            encoding_type = enc.get("encoding", "").lower()
            table_data.append([
                enc.get("column", ""),
                enc.get("encoding", "").replace("_", " ").title(),
                enc.get("reason", "")[:55] + "..." if len(enc.get("reason", "")) > 55 else enc.get("reason", "")
            ])
            row_colors.append(encoding_colors.get(encoding_type, colors.white))

        col_widths = [1.8 * inch, 1.2 * inch, 3.2 * inch]
        table = Table(table_data, colWidths=col_widths)
        style_commands = [
            ("BACKGROUND", (0, 0), (-1, 0), Brand.TABLE_HEADER),
            ("TEXTCOLOR", (0, 0), (-1, 0), Brand.TEXT_LIGHT),
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ("FONTSIZE", (0, 0), (-1, 0), 9), ("FONTSIZE", (0, 1), (-1, -1), 8),
            ("GRID", (0, 0), (-1, -1), 0.5, Brand.DIVIDER),
            ("TOPPADDING", (0, 0), (-1, -1), 4), ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
        ]
        for row_idx, bg_color in enumerate(row_colors, start=1):
            style_commands.append(("BACKGROUND", (1, row_idx), (1, row_idx), bg_color))
        table.setStyle(TableStyle(style_commands))
        story.append(table)
        story.append(Spacer(1, 0.15 * inch))

    scalings = fe.get("scaling_recommendations", [])
    if scalings:
        story.append(Paragraph("<b>Numeric Scaling</b>", styles["TableCaption"]))
        story.append(Spacer(1, 0.05 * inch))
        table_data = [["Column", "Recommended Scaler", "Reason"]]
        for sc in scalings[:8]:
            scaler = sc.get("scaler", "").replace("_", " ").title()
            reason = sc.get("reason", "")[:50]
            table_data.append([sc.get("column", ""), scaler, reason])
        story.append(_build_styled_table(table_data))
        story.append(Spacer(1, 0.15 * inch))

    extractions = fe.get("feature_extraction", [])
    if extractions:
        story.append(Paragraph("<b>Feature Extraction Ideas</b>", styles["TableCaption"]))
        story.append(Spacer(1, 0.05 * inch))
        for ext in extractions[:3]:
            source = ext.get("source", "")
            suggestions = ext.get("suggestions", [])
            if suggestions:
                sugg_text = ", ".join([s.get("name", "") for s in suggestions[:3]])
                story.append(Paragraph(f"From <b>{source}</b>: {sugg_text}", styles["Normal"]))

    story.extend(_divider())
    meta.sections_included.append("Feature Engineering")
    return story


def _build_smart_schema_section(
    analysis_results: dict[str, Any],
    styles: dict[str, ParagraphStyle],
    meta: ReportMetadata,
) -> list[Flowable]:
    """Build section showing smart schema corrections and issues."""
    schema = analysis_results.get("smart_schema")
    if not schema:
        meta.sections_skipped.append({"section": "Smart Schema", "reason": "No schema analysis data."})
        return []

    story: list[Flowable] = []
    story.append(Paragraph("Smart Schema Analysis", styles["SectionHeading"]))
    story.append(Spacer(1, 0.1 * inch))

    corrections = schema.get("type_corrections", [])
    if corrections:
        story.append(Paragraph("<b>Suggested Type Corrections</b>", styles["TableCaption"]))
        story.append(Spacer(1, 0.05 * inch))
        table_data = [["Column", "Current", "Suggested", "Reason"]]
        for corr in corrections[:6]:
            table_data.append([
                corr.get("column", ""), corr.get("current_type", ""),
                corr.get("suggested_type", ""), corr.get("reason", "")[:40]
            ])
        story.append(_build_styled_table(table_data))
        story.append(Spacer(1, 0.15 * inch))

    issues = schema.get("schema_issues", [])
    if issues:
        story.append(Paragraph("<b>Schema Quality Issues</b>", styles["TableCaption"]))
        story.append(Spacer(1, 0.05 * inch))
        for issue in issues[:5]:
            severity = issue.get("severity", "medium")
            sev_icon = "[HIGH]" if severity == "high" else "[MED]" if severity == "medium" else "[LOW]"
            issue_text = f"{sev_icon} <b>{issue.get('column', '')}</b>: {issue.get('description', '')}"
            story.append(Paragraph(issue_text, styles["Normal"]))
            if issue.get("suggestion"):
                story.append(Paragraph(f"  Suggestion: {issue.get('suggestion')}", styles["Body"]))
        story.append(Spacer(1, 0.1 * inch))

    relationships = schema.get("relationships", [])
    if relationships:
        story.append(Paragraph("<b>Detected Relationships</b>", styles["TableCaption"]))
        for rel in relationships[:3]:
            rel_text = f"{rel.get('source', '')} -> {rel.get('target', '')} ({rel.get('type', '')})"
            story.append(Paragraph(rel_text, styles["Normal"]))

    story.extend(_divider())
    meta.sections_included.append("Smart Schema")
    return story


def _build_recommendations_section(
    analysis_results: dict[str, Any],
    styles: dict[str, ParagraphStyle],
    meta: ReportMetadata,
) -> list[Flowable]:
    """Build section showing actionable recommendations with color-coded priorities."""
    recs = analysis_results.get("recommendations")
    if not recs:
        meta.sections_skipped.append({"section": "Recommendations", "reason": "No recommendations data."})
        return []

    story: list[Flowable] = []
    story.append(Paragraph("Actionable Recommendations", styles["SectionHeading"]))
    story.append(Paragraph(
        "Prioritized suggestions based on your data characteristics and detected domain. "
        "Code hints are provided where applicable.",
        styles["Body"]
    ))
    story.append(Spacer(1, 0.1 * inch))

    priority_colors = {
        "high": colors.HexColor("#fee2e2"), "medium": colors.HexColor("#fef3c7"),
        "low": colors.HexColor("#dcfce7"),
    }
    priority_text_colors = {
        "high": colors.HexColor("#dc2626"), "medium": colors.HexColor("#d97706"),
        "low": colors.HexColor("#16a34a"),
    }

    all_recs = (
        recs.get("domain_specific", []) + recs.get("data_quality", []) +
        recs.get("analysis", []) + recs.get("visualization", [])
    )
    priority_order = {"high": 0, "medium": 1, "low": 2}
    all_recs.sort(key=lambda r: priority_order.get(r.get("priority", "low"), 2))

    high_count = sum(1 for r in all_recs if r.get("priority") == "high")
    med_count = sum(1 for r in all_recs if r.get("priority") == "medium")
    total = len(all_recs)

    if total > 0:
        summary_text = f"<b>{total} recommendations</b>: {high_count} high priority, {med_count} medium priority"
        story.append(Paragraph(summary_text, styles["Body"]))
        story.append(Spacer(1, 0.1 * inch))

    for rec in all_recs[:12]:
        priority = rec.get("priority", "medium")
        prio_label = priority.upper()
        text_color = priority_text_colors.get(priority, colors.black)
        title_text = f"<font color='{text_color.hexval()}'><b>[{prio_label}]</b></font> {rec.get('title', '')}"
        story.append(Paragraph(title_text, styles["Normal"]))
        category = rec.get("category", "").replace("_", " ").title()
        story.append(Paragraph(f"<i>{category}</i>: {rec.get('description', '')}", styles["Body"]))
        story.append(Paragraph(f"<b>Action:</b> {rec.get('action', '')}", styles["Body"]))

        code_hint = rec.get("code_hint")
        if code_hint:
            code_text = f"<font name='Courier' size='8' color='#0369a1'><b>→</b> {code_hint}</font>"
            code_para = Paragraph(code_text, styles["Body"])
            code_table = Table([[code_para]], colWidths=[5.8 * inch])
            code_table.setStyle(TableStyle([
                ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#f0f9ff")),
                ("LEFTPADDING", (0, 0), (-1, -1), 8), ("RIGHTPADDING", (0, 0), (-1, -1), 8),
                ("TOPPADDING", (0, 0), (-1, -1), 4), ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
            ]))
            story.append(code_table)
        story.append(Spacer(1, 0.1 * inch))

    story.extend(_divider())
    meta.sections_included.append("Recommendations")
    return story


# ─── Tier 1: Trust Foundation ────────────────────────────────────────────────

def _build_confidence_scores_section(
    analysis_results: dict[str, Any],
    styles: dict[str, ParagraphStyle],
    meta: ReportMetadata,
) -> list:
    """Build section showing column confidence scores with color-coded grades."""
    story = []
    confidence_data = analysis_results.get("confidence_scores")
    if not confidence_data:
        meta.sections_skipped.append("Data Quality Assessment")
        return story

    story.append(Paragraph("Data Quality Assessment", styles["SectionHeading"]))
    story.append(Paragraph(
        "Each column is graded A-F across four dimensions: <b>Completeness</b> (non-null %), "
        "<b>Consistency</b> (format uniformity), <b>Validity</b> (expected ranges), and "
        "<b>Stability</b> (variance detection).",
        styles["Body"]
    ))
    story.append(Spacer(1, 0.15 * inch))

    grade_colors = {
        "A": colors.HexColor("#dcfce7"), "B": colors.HexColor("#dbeafe"),
        "C": colors.HexColor("#fef9c3"), "D": colors.HexColor("#ffedd5"),
        "F": colors.HexColor("#fee2e2"),
    }

    dataset_grade = confidence_data.get("dataset_grade", "N/A")
    dataset_conf = confidence_data.get("dataset_confidence", 0)
    high_count = confidence_data.get("high_confidence_count", 0)
    low_count = confidence_data.get("low_confidence_count", 0)

    story.append(Paragraph(
        f"<b>Dataset Grade: {dataset_grade}</b> ({dataset_conf:.0f}% confidence) — "
        f"{high_count} high-confidence columns, {low_count} low-confidence columns",
        styles["Normal"]
    ))
    story.append(Spacer(1, 0.1 * inch))

    critical = confidence_data.get("critical_issues", [])
    if critical:
        story.append(Paragraph("<b>Issues Detected:</b>", styles["Normal"]))
        for issue in critical[:5]:
            story.append(Paragraph(f"• {issue}", styles["Body"]))
        story.append(Spacer(1, 0.1 * inch))

    columns = confidence_data.get("columns", [])
    if columns:
        header = ["Column", "Grade", "Complete", "Consist", "Valid", "Stable"]
        table_data = [header]
        row_colors = []

        for col in columns[:15]:
            grade = col.get("grade", "?")
            table_data.append([
                col.get("column", "")[:20], grade,
                f"{col.get('completeness', 0):.0f}%", f"{col.get('consistency', 0):.0f}%",
                f"{col.get('validity', 0):.0f}%", f"{col.get('stability', 0):.0f}%",
            ])
            row_colors.append(grade_colors.get(grade, colors.white))

        col_widths = [2.0 * inch, 0.6 * inch, 0.8 * inch, 0.8 * inch, 0.8 * inch, 0.8 * inch]
        table = Table(table_data, colWidths=col_widths)

        style_commands = [
            ("BACKGROUND", (0, 0), (-1, 0), Brand.TABLE_HEADER),
            ("TEXTCOLOR", (0, 0), (-1, 0), Brand.TEXT_LIGHT),
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ("FONTSIZE", (0, 0), (-1, 0), 9), ("FONTSIZE", (0, 1), (-1, -1), 8),
            ("ALIGN", (1, 0), (-1, -1), "CENTER"),
            ("GRID", (0, 0), (-1, -1), 0.5, Brand.DIVIDER),
            ("TOPPADDING", (0, 0), (-1, -1), 4), ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
        ]
        for row_idx, bg_color in enumerate(row_colors, start=1):
            style_commands.append(("BACKGROUND", (1, row_idx), (1, row_idx), bg_color))
        for row_idx in range(1, len(table_data)):
            if row_idx % 2 == 0:
                style_commands.append(("BACKGROUND", (0, row_idx), (0, row_idx), Brand.TABLE_ROW_ALT))
                for col_idx in range(2, 6):
                    style_commands.append(("BACKGROUND", (col_idx, row_idx), (col_idx, row_idx), Brand.TABLE_ROW_ALT))
        table.setStyle(TableStyle(style_commands))
        story.append(table)

    story.extend(_divider())
    meta.sections_included.append("Data Quality Assessment")
    return story


def _build_analysis_decisions_section(
    analysis_results: dict[str, Any],
    styles: dict[str, ParagraphStyle],
    meta: ReportMetadata,
) -> list:
    """Build section showing why each analysis was run or skipped with grouped layout."""
    story = []
    decisions_data = analysis_results.get("analysis_decisions")
    if not decisions_data:
        meta.sections_skipped.append("Methodology & Transparency")
        return story

    story.append(Paragraph("Methodology & Transparency", styles["SectionHeading"]))
    story.append(Paragraph(
        "This section documents which analyses were performed and why. "
        "Transparency ensures decisions are explainable and auditable.",
        styles["Body"]
    ))
    story.append(Spacer(1, 0.15 * inch))

    summary = decisions_data.get("summary", {})
    ran = summary.get("ran", 0)
    skipped = summary.get("skipped", 0)
    total = summary.get("total", 0)

    summary_text = f"""
    <b>Analysis Summary:</b> {ran} of {total} analyses performed<br/>
    <font size="9" color="#6b7280">{skipped} skipped due to data constraints</font>
    """
    summary_para = Paragraph(summary_text.strip(), styles["Body"])
    summary_table = Table([[summary_para]], colWidths=[5.5 * inch])
    summary_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#f0f9ff")),
        ("LEFTPADDING", (0, 0), (-1, -1), 12), ("RIGHTPADDING", (0, 0), (-1, -1), 12),
        ("TOPPADDING", (0, 0), (-1, -1), 8), ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
        ("BOX", (0, 0), (-1, -1), 1, colors.HexColor("#3b82f6")),
    ]))
    story.append(summary_table)
    story.append(Spacer(1, 0.15 * inch))

    decisions = decisions_data.get("decisions", [])
    if decisions:
        status_colors = {
            "ran": colors.HexColor("#dcfce7"), "skipped": colors.HexColor("#fef3c7"),
            "partial": colors.HexColor("#dbeafe"), "failed": colors.HexColor("#fee2e2"),
        }
        table_data = [["Analysis", "Status", "Reason"]]
        row_colors = []
        for d in decisions:
            status = d.get("decision", "")
            status_icon = "✓" if status == "ran" else "○" if status == "skipped" else "◐" if status == "partial" else "✗"
            table_data.append([
                d.get("analysis", "")[:28],
                f"{status_icon} {status.upper()}",
                d.get("reason", "")[:55],
            ])
            row_colors.append(status_colors.get(status, colors.white))

        col_widths = [2.2 * inch, 0.9 * inch, 3.1 * inch]
        table = Table(table_data, colWidths=col_widths)
        style_commands = [
            ("BACKGROUND", (0, 0), (-1, 0), Brand.TABLE_HEADER),
            ("TEXTCOLOR", (0, 0), (-1, 0), Brand.TEXT_LIGHT),
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ("FONTSIZE", (0, 0), (-1, 0), 9), ("FONTSIZE", (0, 1), (-1, -1), 8),
            ("ALIGN", (1, 0), (1, -1), "CENTER"),
            ("GRID", (0, 0), (-1, -1), 0.5, Brand.DIVIDER),
            ("TOPPADDING", (0, 0), (-1, -1), 4), ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
            ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ]
        for row_idx, bg_color in enumerate(row_colors, start=1):
            style_commands.append(("BACKGROUND", (1, row_idx), (1, row_idx), bg_color))
        table.setStyle(TableStyle(style_commands))
        story.append(table)

    story.extend(_divider())
    meta.sections_included.append("Methodology & Transparency")
    return story
