from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Image, Table, TableStyle
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib import colors
from reportlab.lib.units import inch
from io import BytesIO
import base64
import logging

logger = logging.getLogger(__name__)

def generate_pdf_report(analysis_results: dict, charts: dict, filename: str) -> BytesIO:
    """
    Generates a PDF report using ReportLab.
    Returns the PDF as a BytesIO buffer.
    """
    try:
        buffer = BytesIO()
        doc = SimpleDocTemplate(buffer, pagesize=letter)
        story = []
        styles = getSampleStyleSheet()

        # Custom Styles
        title_style = styles["Title"]
        heading_style = styles["Heading2"]
        normal_style = styles["Normal"]
        
        # 1. Title Page
        story.append(Paragraph(f"Data Analysis Report: {filename}", title_style))
        story.append(Spacer(1, 0.25 * inch))
        story.append(Paragraph("Generated by GetReport AI", normal_style))
        story.append(Spacer(1, 0.5 * inch))

        # 2. Executive Summary (from Analysis)
        if "summary" in analysis_results:
            story.append(Paragraph("Executive Summary", heading_style))
            story.append(Spacer(1, 0.1 * inch))
            
            # Convert dictionary summary to Table data
            summary_data = [["Metric", "Value"]]
            # Take just the first column's summary for brevity in this demo, 
            # or iterate nicely. Let's do a generic transpose.
            first_col = list(analysis_results["summary"].keys())[0] 
            metrics = analysis_results["summary"][first_col]
            
            for k, v in metrics.items():
                val = f"{v:.2f}" if isinstance(v, (int, float)) else str(v)
                summary_data.append([k, val])
                
            t = Table(summary_data)
            t.setStyle(TableStyle([
                ('BACKGROUND', (0, 0), (-1, 0), colors.grey),
                ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
                ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
                ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
                ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
                ('BACKGROUND', (0, 1), (-1, -1), colors.beige),
                ('GRID', (0, 0), (-1, -1), 1, colors.black)
            ]))
            story.append(t)
            story.append(Spacer(1, 0.25 * inch))

        # 3. Visualizations
        if "correlation_heatmap" in charts:
            story.append(Paragraph("Correlation Analysis", heading_style))
            story.append(Spacer(1, 0.1 * inch))
            
            # Decode Base64 to Image
            img_data = base64.b64decode(charts["correlation_heatmap"])
            img_io = BytesIO(img_data)
            img = Image(img_io, width=6*inch, height=4.5*inch)
            story.append(img)
            story.append(Spacer(1, 0.25 * inch))

        if "distributions" in charts:
            story.append(Paragraph("Feature Distributions", heading_style))
            for dist in charts["distributions"]:
                story.append(Paragraph(f"Distribution of {dist['column']}", normal_style))
                img_data = base64.b64decode(dist["image"])
                img_io = BytesIO(img_data)
                img = Image(img_io, width=5*inch, height=3*inch)
                story.append(img)
                story.append(Spacer(1, 0.1 * inch))

        doc.build(story)
        buffer.seek(0)
        return buffer

    except Exception as e:
        logger.error(f"Error generating PDF: {str(e)}")
        raise e
